# Benchmark configurations
module: multimodal  # required
mode: local  # required
benchmark_name: ag_bench  # required
root_dir: ag_bench_runs  # optional, default = "ag_bench_runs"

# Multimodal specific
framework: AutoGluon_stable  # required
dataset_name:  # required
  fake

#### Customizations ####
custom_resource_dir: sample_configs/resources/  # path to custom multimodal_frameworks.yaml and multimodal_constraints.yaml
custom_dataloader:
    dataloader_file: sample_configs/dataloaders/text_tabular_image_dataloader.py   # relative path to WORKDIR
    class_name: TextTabularImageDataLoader
    dataset_config_file: sample_configs/dataloaders/all_datasets.yaml
